import { chromium } from "playwright-core";
const exe = process.env.HOME + "/Library/Caches/ms-playwright/chromium-1208/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";
const b = await chromium.launch({ executablePath: exe, args: ["--autoplay-policy=no-user-gesture-required", "--mute-audio"] });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const errs = []; p.on("pageerror", e => errs.push(e.message)); p.on("console", m => { if (m.type() === "error") errs.push("console: " + m.text()); });
await p.goto("http://localhost:4070/"); await p.waitForTimeout(900);
console.log("coreografias:", await p.evaluate(() => document.querySelectorAll(".coreo").length), "| faixas:", await p.evaluate(() => document.querySelectorAll(".faixa").length));
console.log("rodapé:", await p.evaluate(() => document.querySelector("#rodape").textContent));
await p.tap('.faixa[data-id="3-1a"]'); await p.waitForFunction(() => document.querySelector("#au").duration > 0, null, { timeout: 15000 });
console.log("player:", await p.evaluate(() => document.querySelector("#pTit").textContent), "|", await p.evaluate(() => document.querySelector("#pTema").textContent), "| dur:", await p.evaluate(() => Math.round(document.querySelector("#au").duration)));
await p.tap("#btnPlay"); await p.waitForTimeout(1200);
console.log("tocando:", await p.evaluate(() => !document.querySelector("#au").paused), "| preservesPitch:", await p.evaluate(() => document.querySelector("#au").preservesPitch));
await p.tap('[data-vel="-"]'); await p.tap('[data-vel="-"]'); await p.waitForTimeout(300);
console.log("velocidade:", await p.evaluate(() => document.querySelector("#au").playbackRate.toFixed(2)), "| mostra:", await p.evaluate(() => document.querySelector("#velTxt").textContent));
await p.evaluate(() => document.querySelector("#au").currentTime = 20); await p.tap("#btnIni"); await p.waitForTimeout(300);
await p.evaluate(() => document.querySelector("#au").currentTime = 50); await p.tap("#btnFim"); await p.waitForTimeout(400);
console.log("faixa continua a mesma depois de marcar o fim:", await p.evaluate(() => document.querySelector("#pTit").textContent));
console.log("corte salvo:", await p.evaluate(() => JSON.parse(localStorage.getItem("palco.ajustes"))["3-1a"]));
await p.tap('[data-add]'); await p.waitForTimeout(300);
console.log("pontos:", await p.evaluate(() => JSON.parse(localStorage.getItem("palco.ajustes"))["3-1a"].pts), "| botões:", await p.evaluate(() => document.querySelectorAll("#ptsBox .p").length));
await p.evaluate(() => document.querySelector("#au").currentTime = 25); await p.tap("#btnA"); await p.evaluate(() => document.querySelector("#au").currentTime = 30); await p.tap("#btnB"); await p.tap("#btnPlay"); await p.waitForTimeout(2500);
console.log("loop A-B segurando:", await p.evaluate(() => Math.round(document.querySelector("#au").currentTime)), "(tem que ficar entre 25 e 31)");
await p.tap("#btnLimpaAB"); await p.tap("#btnVoltar"); await p.waitForTimeout(400);
console.log("lista mostra corte:", await p.evaluate(() => document.querySelector('.faixa[data-id="3-1a"] .dur').textContent));
await p.tap('[data-modo="show"]'); await p.waitForTimeout(300);
await p.tap('.faixa[data-id="6-1"]'); await p.waitForTimeout(800);
console.log("modo show, controles escondidos:", await p.evaluate(() => document.querySelectorAll("#controles .bloco").length === 0), "| próxima:", await p.evaluate(() => document.querySelector("#prox").textContent.trim()));
await p.screenshot({ path: "tela-player.png" });
await p.tap("#btnVoltar"); await p.waitForTimeout(300); await p.screenshot({ path: "tela-lista.png" });
console.log("erros:", errs.length ? errs : "nenhum"); await b.close();
